language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
install:
  - pip install python-coveralls coverage
  - pip install -r requirements.txt
  - pip install -r requirements_diagrams.txt
  - pip install -r requirements_test.txt
script:  nosetests --with-coverage --with-doctest
after_success:
  - coveralls --config_file .coveragerc
sudo: false
addons:
  apt:
    packages:
      - graphviz