language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install python-coveralls 'coverage<5'
  - pip install -r requirements.txt
  - pip install -r requirements_diagrams.txt
  - pip install -r requirements_test.txt
script: pytest --doctest-modules --cov transitions/
after_success:
  - coveralls --config_file .coveragerc
addons:
  apt:
    packages:
      - graphviz
